window.SHORTCUT_APPS = [
  {
    id: "windows",
    name: "Windows 11",
    icon: "⊞",
    category: "System",
    platform: "windows",
    popular: true,
    accent: "#3b82f6",
    description: "Desktop, windows, screenshots and system navigation.",
    source: "https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec",
    shortcuts: [
      { action: "Show / hide desktop", windows: "Win + D" },
      { action: "Open File Explorer", windows: "Win + E" },
      { action: "Open Settings", windows: "Win + I" },
      { action: "Lock your PC", windows: "Win + L" },
      { action: "Open clipboard history", windows: "Win + V" },
      { action: "Open snipping overlay", windows: "Win + Shift + S" },
      { action: "Switch open apps", windows: "Alt + Tab" },
      { action: "Open Task View", windows: "Win + Tab" },
      { action: "Open Task Manager", windows: "Ctrl + Shift + Esc" },
      { action: "Create a virtual desktop", windows: "Win + Ctrl + D" }
    ]
  },
  {
    id: "macos",
    name: "macOS",
    icon: "⌘",
    category: "System",
    platform: "mac",
    popular: true,
    accent: "#8b95a7",
    description: "Everyday Mac navigation and system controls.",
    source: "https://support.apple.com/en-us/102650",
    shortcuts: [
      { action: "Open Spotlight", mac: "Command + Space" },
      { action: "Switch apps", mac: "Command + Tab" },
      { action: "Lock your Mac", mac: "Control + Command + Q" },
      { action: "Screenshot / recording tools", mac: "Shift + Command + 5" },
      { action: "Force quit an app", mac: "Option + Command + Esc" },
      { action: "Open Mission Control", mac: "Control + ↑" },
      { action: "Hide current app", mac: "Command + H" },
      { action: "Minimize current window", mac: "Command + M" },
      { action: "Quit current app", mac: "Command + Q" },
      { action: "Redo", mac: "Shift + Command + Z" }
    ]
  },
  {
    id: "chrome",
    name: "Google Chrome",
    icon: "Ch",
    category: "Browser",
    platform: "both",
    popular: true,
    accent: "#34a853",
    description: "Tabs, browsing, search, history and downloads.",
    source: "https://support.google.com/chrome/answer/157179",
    shortcuts: [
      { action: "Open a new tab", windows: "Ctrl + T", mac: "Command + T" },
      { action: "Open a new window", windows: "Ctrl + N", mac: "Command + N" },
      { action: "Open Incognito window", windows: "Ctrl + Shift + N", mac: "Command + Shift + N" },
      { action: "Reopen last closed tab", windows: "Ctrl + Shift + T", mac: "Command + Shift + T" },
      { action: "Focus address bar", windows: "Ctrl + L", mac: "Command + L" },
      { action: "Find on page", windows: "Ctrl + F", mac: "Command + F" },
      { action: "Bookmark current page", windows: "Ctrl + D", mac: "Command + D" },
      { action: "Open downloads", windows: "Ctrl + J", mac: "Command + Shift + J" },
      { action: "Open history", windows: "Ctrl + H", mac: "Command + Y" },
      { action: "Close current tab", windows: "Ctrl + W", mac: "Command + W" }
    ]
  },
  {
    id: "word",
    name: "Microsoft Word",
    icon: "W",
    category: "Office",
    platform: "both",
    popular: true,
    accent: "#2b579a",
    description: "Writing, formatting, reviewing and document navigation.",
    source: "https://support.microsoft.com/en-us/accessibility/word/keyboard-shortcuts-in-word",
    shortcuts: [
      { action: "Save document", windows: "Ctrl + S", mac: "Command + S" },
      { action: "Bold selected text", windows: "Ctrl + B", mac: "Command + B" },
      { action: "Italic selected text", windows: "Ctrl + I", mac: "Command + I" },
      { action: "Underline selected text", windows: "Ctrl + U", mac: "Command + U" },
      { action: "Insert hyperlink", windows: "Ctrl + K", mac: "Command + K" },
      { action: "Find text", windows: "Ctrl + F", mac: "Command + F" },
      { action: "Replace text", windows: "Ctrl + H", mac: "Control + H" },
      { action: "Select all", windows: "Ctrl + A", mac: "Command + A" },
      { action: "Print document", windows: "Ctrl + P", mac: "Command + P" },
      { action: "Undo", windows: "Ctrl + Z", mac: "Command + Z" }
    ]
  },
  {
    id: "excel",
    name: "Microsoft Excel",
    icon: "X",
    category: "Office",
    platform: "both",
    popular: true,
    accent: "#217346",
    description: "Workbook editing, selection and formatting essentials.",
    source: "https://support.microsoft.com/en-us/accessibility/excel/keyboard-shortcuts-in-excel",
    shortcuts: [
      { action: "Save workbook", windows: "Ctrl + S", mac: "Command + S" },
      { action: "Open Format Cells", windows: "Ctrl + 1", mac: "Command + 1" },
      { action: "Find", windows: "Ctrl + F", mac: "Command + F" },
      { action: "Select entire column", windows: "Ctrl + Space", mac: "Control + Space" },
      { action: "Select entire row", windows: "Shift + Space", mac: "Shift + Space" },
      { action: "Bold cells", windows: "Ctrl + B", mac: "Command + B" },
      { action: "Copy", windows: "Ctrl + C", mac: "Command + C" },
      { action: "Paste", windows: "Ctrl + V", mac: "Command + V" },
      { action: "Undo", windows: "Ctrl + Z", mac: "Command + Z" },
      { action: "Print", windows: "Ctrl + P", mac: "Command + P" }
    ]
  },
  {
    id: "powerpoint",
    name: "PowerPoint",
    icon: "P",
    category: "Office",
    platform: "both",
    popular: true,
    accent: "#d24726",
    description: "Build slides faster with editing and formatting shortcuts.",
    source: "https://support.microsoft.com/en-us/accessibility/powerpoint/use-keyboard-shortcuts-to-create-powerpoint-presentations",
    shortcuts: [
      { action: "Save presentation", windows: "Ctrl + S", mac: "Command + S" },
      { action: "Duplicate selected object / slide", windows: "Ctrl + D", mac: "Command + D" },
      { action: "Group selected objects", windows: "Ctrl + G", mac: "Command + Option + G" },
      { action: "Bold selected text", windows: "Ctrl + B", mac: "Command + B" },
      { action: "Insert hyperlink", windows: "Ctrl + K", mac: "Command + K" },
      { action: "Find", windows: "Ctrl + F", mac: "Command + F" },
      { action: "Select all", windows: "Ctrl + A", mac: "Command + A" },
      { action: "Copy", windows: "Ctrl + C", mac: "Command + C" },
      { action: "Paste", windows: "Ctrl + V", mac: "Command + V" },
      { action: "Undo", windows: "Ctrl + Z", mac: "Command + Z" }
    ]
  },
  {
    id: "vscode",
    name: "Visual Studio Code",
    icon: "VS",
    category: "Development",
    platform: "both",
    popular: true,
    accent: "#007acc",
    description: "Navigate code, edit lines and command the editor quickly.",
    source: "https://code.visualstudio.com/docs/reference/default-keybindings",
    shortcuts: [
      { action: "Show Command Palette", windows: "Ctrl + Shift + P", mac: "Command + Shift + P" },
      { action: "Quick Open / go to file", windows: "Ctrl + P", mac: "Command + P" },
      { action: "Toggle integrated terminal", windows: "Ctrl + `", mac: "Control + `" },
      { action: "Toggle primary side bar", windows: "Ctrl + B", mac: "Command + B" },
      { action: "Search across files", windows: "Ctrl + Shift + F", mac: "Command + Shift + F" },
      { action: "Toggle line comment", windows: "Ctrl + /", mac: "Command + /" },
      { action: "Move line up", windows: "Alt + ↑", mac: "Option + ↑" },
      { action: "Move line down", windows: "Alt + ↓", mac: "Option + ↓" },
      { action: "Copy line down", windows: "Shift + Alt + ↓", mac: "Shift + Option + ↓" },
      { action: "Go to definition", windows: "F12", mac: "F12" }
    ]
  },
  {
    id: "photoshop",
    name: "Adobe Photoshop",
    icon: "Ps",
    category: "Design",
    platform: "both",
    popular: true,
    accent: "#31a8ff",
    description: "Tools, selections, layers and transforms for faster editing.",
    source: "https://helpx.adobe.com/photoshop/desktop/get-started/settings-and-preferences/view-keyboard-shortcuts.html",
    shortcuts: [
      { action: "Move tool", windows: "V", mac: "V" },
      { action: "Brush tool", windows: "B", mac: "B" },
      { action: "Type tool", windows: "T", mac: "T" },
      { action: "Free Transform", windows: "Ctrl + T", mac: "Command + T" },
      { action: "Duplicate layer", windows: "Ctrl + J", mac: "Command + J" },
      { action: "Deselect", windows: "Ctrl + D", mac: "Command + D" },
      { action: "Levels", windows: "Ctrl + L", mac: "Command + L" },
      { action: "Hue / Saturation", windows: "Ctrl + U", mac: "Command + U" },
      { action: "Save", windows: "Ctrl + S", mac: "Command + S" },
      { action: "Keyboard shortcuts dialog", windows: "Alt + Shift + Ctrl + K", mac: "Option + Shift + Command + K" }
    ]
  },
  {
    id: "canva",
    name: "Canva",
    icon: "C",
    category: "Design",
    platform: "both",
    popular: true,
    accent: "#7d2ae8",
    description: "Common editor actions for fast layout and design work.",
    source: "https://www.canva.com/help/canva-keyboard-shortcuts/",
    shortcuts: [
      { action: "Open Quick actions", windows: "Ctrl + E", mac: "Command + E" },
      { action: "Copy", windows: "Ctrl + C", mac: "Command + C" },
      { action: "Paste", windows: "Ctrl + V", mac: "Command + V" },
      { action: "Duplicate selection", windows: "Ctrl + D", mac: "Command + D" },
      { action: "Group selection", windows: "Ctrl + G", mac: "Command + G" },
      { action: "Ungroup selection", windows: "Ctrl + Shift + G", mac: "Command + Shift + G" },
      { action: "Select all", windows: "Ctrl + A", mac: "Command + A" },
      { action: "Bold text", windows: "Ctrl + B", mac: "Command + B" },
      { action: "Undo", windows: "Ctrl + Z", mac: "Command + Z" },
      { action: "Delete selection", windows: "Delete", mac: "Delete" }
    ]
  },
  {
    id: "figma",
    name: "Figma",
    icon: "Fi",
    category: "Design",
    platform: "both",
    popular: true,
    accent: "#f24e1e",
    description: "Design tools, frames, auto layout and object editing.",
    source: "https://help.figma.com/hc/en-us/articles/360040328653-Use-Figma-products-with-a-keyboard",
    shortcuts: [
      { action: "Open keyboard shortcuts panel", windows: "Ctrl + Shift + ?", mac: "Control + Shift + ?" },
      { action: "Add Auto layout", windows: "Shift + A", mac: "Shift + A" },
      { action: "Frame tool", windows: "F", mac: "F" },
      { action: "Pen tool", windows: "P", mac: "P" },
      { action: "Text tool", windows: "T", mac: "T" },
      { action: "Rectangle tool", windows: "R", mac: "R" },
      { action: "Ellipse tool", windows: "O", mac: "O" },
      { action: "Duplicate selection", windows: "Ctrl + D", mac: "Command + D" },
      { action: "Group selection", windows: "Ctrl + G", mac: "Command + G" },
      { action: "Show / hide UI", windows: "Ctrl + \\", mac: "Command + \\" }
    ]
  },
  {
    id: "github",
    name: "GitHub",
    icon: "GH",
    category: "Development",
    platform: "both",
    popular: true,
    accent: "#6e7681",
    description: "Navigate repositories, code, issues and pull requests.",
    source: "https://docs.github.com/en/get-started/accessibility/keyboard-shortcuts",
    shortcuts: [
      { action: "Show shortcuts for current page", windows: "?", mac: "?" },
      { action: "Focus site search", windows: "S", mac: "S" },
      { action: "Go to notifications", windows: "G → N", mac: "G → N" },
      { action: "Go to Code tab", windows: "G → C", mac: "G → C" },
      { action: "Go to Issues tab", windows: "G → I", mac: "G → I" },
      { action: "Go to Pull requests tab", windows: "G → P", mac: "G → P" },
      { action: "Go to Actions tab", windows: "G → A", mac: "G → A" },
      { action: "Open repository in github.dev", windows: ".", mac: "." },
      { action: "Activate file finder", windows: "T", mac: "T" },
      { action: "Submit a comment", windows: "Ctrl + Enter", mac: "Command + Enter" }
    ]
  },
  {
    id: "slack",
    name: "Slack",
    icon: "Sl",
    category: "Communication",
    platform: "both",
    popular: false,
    accent: "#611f69",
    description: "Search, conversations, windows and huddle controls.",
    source: "https://slack.com/help/articles/201374536-Slack-keyboard-shortcuts",
    shortcuts: [
      { action: "Start a search", windows: "Ctrl + G", mac: "Command + G" },
      { action: "Search current conversation", windows: "Ctrl + F", mac: "Command + F" },
      { action: "Start / join / leave a huddle", windows: "Ctrl + Shift + H", mac: "Command + Shift + H" },
      { action: "Toggle huddle mute", windows: "Ctrl + Shift + Space", mac: "Command + Shift + Space" },
      { action: "Open People view", windows: "Ctrl + Shift + E", mac: "Command + Shift + E" },
      { action: "Close window", windows: "Ctrl + W", mac: "Command + W" },
      { action: "Reopen last closed window", windows: "Ctrl + Shift + W", mac: "Command + Shift + W" },
      { action: "Open Help", windows: "F1", mac: "F1" },
      { action: "Toggle full screen", windows: "F11", mac: "Control + Command + F" },
      { action: "Add emoji reaction to message", windows: "Ctrl + Shift + \\", mac: "Command + Shift + \\" }
    ]
  }
];
