(()=>{const safeStore={
  get(key,fallback=null){try{const v=window.localStorage.getItem(key);return v===null?fallback:v}catch{return fallback}},
  set(key,value){try{window.localStorage.setItem(key,value)}catch{}}
};
function safeJSON(value,fallback=[]){try{return JSON.parse(value)}catch{return fallback}}
const apps=window.SHORTCUT_APPS||[];const PAGE=30;const $=id=>document.getElementById(id);const el={grid:$('appGrid'),search:$('searchInput'),cat:$('categorySelect'),prof:$('professionSelect'),fav:$('favoritesToggle'),theme:$('themeToggle'),themeIcon:$('themeIcon'),count:$('resultCount'),title:$('resultsTitle'),empty:$('emptyState'),reset:$('resetButton'),loadWrap:$('loadMoreWrap'),load:$('loadMoreButton'),software:$('softwareStat'),shortcut:$('shortcutStat'),verified:$('verifiedStat'),categories:$('categoryStat'),toast:$('toast'),dialog:$('detailDialog'),close:$('dialogClose'),dLogo:$('detailLogo'),dCat:$('detailCategory'),dCov:$('detailCoverage'),dName:$('detailName'),dDesc:$('detailDescription'),dSource:$('detailSource'),dSearch:$('detailSearch'),dCount:$('detailCount'),dGroups:$('detailGroups'),momentLogo:$('momentLogo'),momentApp:$('momentApp'),momentAction:$('momentAction'),momentKeys:$('momentKeys')};
const state={platform:safeStore.get('shv2Platform')==='mac'?'mac':'windows',category:'All',profession:'All',status:'all',query:'',favoritesOnly:false,favorites:new Set(safeJSON(safeStore.get('shv2Favorites','[]'),[])),limit:PAGE,detailApp:null,detailQuery:''};
const categories=['All',...new Set(apps.map(a=>a.category).filter(Boolean))].sort((a,b)=>a==='All'?-1:b==='All'?1:a.localeCompare(b));const professions=['All',...new Set(apps.flatMap(a=>a.professions||[]))].sort((a,b)=>a==='All'?-1:b==='All'?1:a.localeCompare(b));
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const aliases={windows:'windows11',macos:'apple',chrome:'googlechrome',word:'microsoftword',excel:'microsoftexcel',powerpoint:'microsoftpowerpoint',vscode:'visualstudiocode',photoshop:'adobephotoshop',illustrator:'adobeillustrator',premiere:'adobepremierepro',aftereffects:'adobeaftereffects',figma:'figma',canva:'canva',github:'github',autocad:'autocad',revit:'autodeskrevit',sketchup:'sketchup',blender:'blender',unreal:'unrealengine',unity:'unity',capcut:'capcut'};
const logoOverrides={word:['https://www.google.com/s2/favicons?domain_url=https://word.cloud.microsoft&sz=256','https://api.iconify.design/logos/microsoft-word.svg'],excel:['https://www.google.com/s2/favicons?domain_url=https://excel.cloud.microsoft&sz=256','https://api.iconify.design/logos/microsoft-excel.svg'],powerpoint:['https://www.google.com/s2/favicons?domain_url=https://powerpoint.cloud.microsoft&sz=256','https://api.iconify.design/logos/microsoft-powerpoint.svg'],photoshop:['https://api.iconify.design/logos/adobe-photoshop.svg','https://api.iconify.design/skill-icons/photoshop.svg'],illustrator:['https://api.iconify.design/logos/adobe-illustrator.svg'],premiere:['https://api.iconify.design/logos/adobe-premiere.svg'],aftereffects:['https://api.iconify.design/logos/adobe-after-effects.svg']};
function logoCandidates(app){const s=[];if(logoOverrides[app.id])s.push(...logoOverrides[app.id]);for(const slug of [app.logoSlug,aliases[app.id],app.id].filter(Boolean))s.push(`https://cdn.simpleicons.org/${encodeURIComponent(slug)}?viewbox=auto&size=64`);let domain=app.logoDomain;try{if(!domain&&app.source)domain=new URL(app.source).hostname.replace(/^www\./,'')}catch{}if(domain)s.push(`https://www.google.com/s2/favicons?domain_url=https://${encodeURIComponent(domain)}&sz=128`);return [...new Set(s)]}
function logoHTML(app,cls=''){return `<span class="${cls}" data-logo-box="${esc(app.id)}"><img data-logo="${esc(app.id)}" alt="" loading="lazy"><b data-logo-fallback>${esc(app.icon||app.name.slice(0,2))}</b></span>`}
function hydrate(root=document){root.querySelectorAll('img[data-logo]').forEach(img=>{if(img.dataset.ready)return;img.dataset.ready='1';const app=apps.find(a=>a.id===img.dataset.logo),cand=app?logoCandidates(app):[];let i=0;const fb=img.parentElement.querySelector('[data-logo-fallback]');const next=()=>{if(i>=cand.length){img.hidden=true;if(fb)fb.hidden=false;return}img.src=cand[i++]};img.onerror=next;img.onload=()=>{if(fb)fb.hidden=true};next()})}
function combo(s){return s?.[state.platform]||''}function parts(c){if(c.includes(' → '))return[c.split(' → '),'→'];if(c.includes(' + '))return[c.split(' + '),'+'];return[[c],'']}function keys(c){const[p,sep]=parts(c);return p.map((k,i)=>`<kbd class="keycap">${esc(k)}</kbd>${i<p.length-1?`<span class="plus">${sep}</span>`:''}`).join('')}
function supports(a){return a.platform==='both'||a.platform===state.platform}function verified(a){return(a.shortcuts||[]).some(combo)}function favId(a,i){return`${a.id}:${i}`}
function matches(){const q=state.query.toLowerCase();return apps.filter(supports).map(a=>{const shortcuts=(a.shortcuts||[]).map((s,i)=>({...s,_i:i})).filter(s=>combo(s));const matched=shortcuts.filter(s=>!q||`${a.name} ${a.category} ${(a.professions||[]).join(' ')} ${s.action} ${combo(s)}`.toLowerCase().includes(q));const appHit=!q||`${a.name} ${a.category} ${(a.professions||[]).join(' ')} ${a.description||''}`.toLowerCase().includes(q);return{...a,_shortcuts:appHit?shortcuts:matched,_appHit:appHit}}).filter(a=>(state.category==='All'||a.category===state.category)&&(state.profession==='All'||(a.professions||[]).includes(state.profession))&&(state.status==='all'||(state.status==='verified'&&verified(a))||(state.status==='catalog'&&!verified(a)))&&(!q||a._appHit||a._shortcuts.length)&&(state.favoritesOnly?a._shortcuts.some(s=>state.favorites.has(favId(a,s._i))):true))}
function essential(a){let list=a._shortcuts||[];if(state.query)return list.slice(0,6);let e=list.filter(s=>s.essential);if(!e.length)e=list.slice(0,6);return e.slice(0,6)}
function card(a){const v=verified(a),ess=essential(a),count=(a.shortcuts||[]).filter(combo).length;return `<article class="app-card" style="--app:${esc(a.accent||'#8b6cff')}"><header class="app-head">${logoHTML(a,'app-logo')}<div class="app-info"><div class="app-name-row"><h3 class="app-name">${esc(a.name)}</h3><span class="verified-pill ${v?'':'catalog-pill'}">${v?'SHORTCUT PACK':'CATALOG'}</span></div><p class="app-desc">${esc(a.description||a.category)}</p></div></header><div class="app-meta"><span>${esc(a.category)}</span><span>${v?`${count} shortcuts`:'awaiting pack'}</span></div>${v?`<div class="essential-list">${ess.map(s=>`<div class="shortcut-row"><span class="shortcut-action">${esc(s.action)}</span><span class="keys">${keys(combo(s))}</span></div>`).join('')}</div><div class="card-actions"><button class="view-all" data-open="${esc(a.id)}">View all ${count} shortcuts</button>${a.source?`<a class="official-link" href="${esc(a.source)}" target="_blank" rel="noreferrer" title="Official reference">↗</a>`:''}</div>`:`<div class="catalog-state"><strong>Software indexed — shortcut pack pending</strong>ShortcutHub keeps the title searchable without publishing guessed defaults.</div>`}</article>`}
function renderFilters(){el.cat.innerHTML=categories.map(x=>`<option ${x===state.category?'selected':''}>${esc(x)}</option>`).join('');el.prof.innerHTML=professions.map(x=>`<option ${x===state.profession?'selected':''}>${esc(x)}</option>`).join('');document.querySelectorAll('.platform-button').forEach(b=>b.classList.toggle('active',b.dataset.platform===state.platform));document.querySelectorAll('.status-button').forEach(b=>b.classList.toggle('active',b.dataset.status===state.status))}
function render(){const all=matches(),shown=all.slice(0,state.limit),sc=all.reduce((n,a)=>n+a._shortcuts.length,0);el.title.textContent=state.favoritesOnly?'Your favorites':state.query?`Results for “${state.query}”`:state.profession!=='All'?state.profession:state.category!=='All'?state.category:state.status==='verified'?'Software with shortcut packs':state.status==='catalog'?'Catalog awaiting packs':'All software';el.count.textContent=`${all.length.toLocaleString()} software · ${sc.toLocaleString()} matching shortcuts`;el.grid.innerHTML=shown.map(card).join('');el.grid.hidden=!shown.length;el.empty.hidden=!!shown.length;el.loadWrap.hidden=all.length<=shown.length;if(!el.loadWrap.hidden)el.load.textContent=`Load ${Math.min(PAGE,all.length-shown.length)} more · ${all.length-shown.length} remaining`;hydrate(el.grid)}
function stats(){el.software.textContent=apps.length.toLocaleString();el.shortcut.textContent=apps.reduce((n,a)=>n+(a.shortcuts||[]).length,0).toLocaleString();el.verified.textContent=apps.filter(a=>(a.shortcuts||[]).length).length.toLocaleString();el.categories.textContent=new Set(apps.map(a=>a.category)).size.toLocaleString()}
function setTheme(t){document.documentElement.dataset.theme=t;safeStore.set('shv2Theme',t);el.themeIcon.textContent=t==='dark'?'☀':'☾'}setTheme(safeStore.get('shv2Theme')||'dark');
function toast(t){el.toast.textContent=t;el.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove('show'),1500)}async function copy(t){try{await navigator.clipboard.writeText(t)}catch{}toast(`Copied: ${t}`)}
function detailGroups(){const a=state.detailApp;if(!a)return;const q=state.detailQuery.toLowerCase();const list=(a.shortcuts||[]).map((s,i)=>({...s,_i:i})).filter(s=>combo(s)&&(!q||`${s.action} ${combo(s)} ${s.group||''}`.toLowerCase().includes(q)));el.dCount.textContent=list.length;const groups=[...new Set(list.map(s=>s.group||'General'))];el.dGroups.innerHTML=groups.map(g=>`<section class="shortcut-group"><h3>${esc(g)}</h3><div class="detail-shortcuts">${list.filter(s=>(s.group||'General')===g).map(s=>`<div class="detail-row"><span class="shortcut-action">${esc(s.action)}</span><span class="keys">${keys(combo(s))}</span><button data-copy="${esc(combo(s))}" title="Copy">⧉</button></div>`).join('')}</div></section>`).join('')||'<div class="empty"><p>No shortcuts match inside this software.</p></div>'}
function openDetail(id){const a=apps.find(x=>x.id===id);if(!a||!verified(a))return;state.detailApp=a;state.detailQuery='';el.dSearch.value='';el.dLogo.innerHTML=logoHTML(a,'detail-logo-inner');el.dCat.textContent=a.category;el.dCov.textContent=(a.coverage||'verified').replaceAll('-',' ');el.dName.textContent=a.name;el.dDesc.textContent=a.description||'';if(a.source){el.dSource.href=a.source;el.dSource.hidden=false}else el.dSource.hidden=true;detailGroups();el.dialog.showModal();hydrate(el.dLogo);history.replaceState(null,'',`#app=${encodeURIComponent(a.id)}`)}
function closeDetail(){if(el.dialog.open)el.dialog.close();state.detailApp=null;if(location.hash.startsWith('#app='))history.replaceState(null,'',location.pathname+location.search)}
function randomPick(open=false){const pool=[];apps.filter(supports).forEach(a=>(a.shortcuts||[]).forEach((s,i)=>{if(combo(s))pool.push({a,s,i})}));if(!pool.length)return;const p=pool[Math.floor(Math.random()*pool.length)];$('momentApp').textContent=p.a.name;$('momentAction').textContent=p.s.action;$('momentKeys').innerHTML=keys(combo(p.s));el.momentLogo.innerHTML=logoHTML(p.a,'moment-logo-inner');hydrate(el.momentLogo);if(open){openDetail(p.a.id);el.dSearch.value=p.s.action;state.detailQuery=p.s.action;detailGroups();toast(`${p.a.name} · ${combo(p.s)}`)}}
function reset(){Object.assign(state,{category:'All',profession:'All',status:'all',query:'',favoritesOnly:false,limit:PAGE});el.search.value='';el.fav.setAttribute('aria-pressed','false');renderFilters();render()}
document.querySelectorAll('.platform-button').forEach(b=>b.onclick=()=>{state.platform=b.dataset.platform;safeStore.set('shv2Platform',state.platform);state.limit=PAGE;renderFilters();render();if(state.detailApp)detailGroups()});document.querySelectorAll('.status-button').forEach(b=>b.onclick=()=>{state.status=b.dataset.status;state.limit=PAGE;renderFilters();render()});el.cat.onchange=e=>{state.category=e.target.value;state.limit=PAGE;render()};el.prof.onchange=e=>{state.profession=e.target.value;state.limit=PAGE;render()};el.search.oninput=e=>{state.query=e.target.value.trim();state.limit=PAGE;render()};el.load.onclick=()=>{state.limit+=PAGE;render()};el.reset.onclick=reset;el.theme.onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');el.fav.onclick=()=>{state.favoritesOnly=!state.favoritesOnly;el.fav.setAttribute('aria-pressed',String(state.favoritesOnly));render()};el.grid.onclick=e=>{const b=e.target.closest('[data-open]');if(b)openDetail(b.dataset.open)};el.close.onclick=closeDetail;el.dialog.addEventListener('click',e=>{if(e.target===el.dialog)closeDetail()});el.dSearch.oninput=e=>{state.detailQuery=e.target.value.trim();detailGroups()};el.dGroups.onclick=e=>{const b=e.target.closest('[data-copy]');if(b)copy(b.dataset.copy)};$('surpriseTop').onclick=()=>randomPick(true);$('surpriseHero').onclick=()=>randomPick(true);$('nextMoment').onclick=()=>randomPick(false);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'&&!el.dialog.open){e.preventDefault();el.search.focus()}if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();el.search.focus()}if(e.key==='Escape'&&el.dialog.open)closeDetail()});
renderFilters();stats();render();randomPick(false);if(location.hash.startsWith('#app='))openDetail(decodeURIComponent(location.hash.slice(5)));})();